/**
 * `repr(_make_hashable(value))` — Python's canonical form of a DataPoint value, reproduced exactly.
 *
 * Python's `canonical_value` (`orcastork/datapoints/base.py`) is literally
 * `repr(_make_hashable(value))`, and that string is **on the wire**: the Redis store's hash field is
 * `f'{type}\x00{canonical_value(value)}'`, and the archive key is a SHA-256 (non-PII) or a keyed MAC
 * (PII) over it. A TypeScript worker that canonicalized a value its own way would dedup against
 * itself and nothing else — the same DataPoint would occupy two Redis fields and two archive rows in
 * a deployment where both runtimes drive the same flow. So this module reproduces CPython's `repr`,
 * byte for byte, rather than inventing a second canonical form.
 *
 * The normalization is Python's `_make_hashable`: arrays and sets become tuples, objects become a
 * tuple of `(key, value)` pairs sorted as Python sorts them. What is left is `repr` of that tuple
 * tree, which this module implements for the JSON-native domain `canonical_value` is specified over:
 * `None`, `True`/`False`, ints, floats, strings and tuples.
 *
 * **What a JavaScript value cannot tell us.** JavaScript has one number type, so the port carries two
 * documented limits, both of them inherent rather than fixable:
 *
 * - A Python `float` whose value is integral reprs with its point (`1.0`, `-0.0`, `1e+16`), while the
 *   JavaScript number `1` cannot know it was ever a float. An integral number is therefore rendered
 *   as Python renders the **int** of the same value (`1`, `0`, `10000000000000000`), which is what a
 *   JSON document written by a Python worker round-trips to anyway (`json.dumps(1)` reads back as
 *   `int`). A value a Python flow holds as `1.0` canonicalizes differently in the two runtimes.
 * - An integer beyond 2^53 does not survive as a JavaScript number at all: `JSON.parse` rounds
 *   `9007199254740993` to `9007199254740992`, and the canonical form follows the rounded value.
 *
 * Everything else — the float digits, the fixed-vs-exponent rule, string escaping, key ordering — is
 * exact, and `tests/internal/python_repr.test.ts` pins it against fixtures generated by CPython
 * itself.
 *
 * @module
 */

import { UnstableValueError } from '../exceptions.js';

/**
 * A value in Python's terms, after `_make_hashable` — the shapes `repr` distinguishes.
 *
 * The normalization and the rendering are separate passes because the sort `_make_hashable` performs
 * on a dict's items and a set's members is a comparison **on Python values**, not on their text: an
 * `int` and a `float` compare numerically, and a `str` and an `int` do not compare at all.
 */
type PyValue =
  | { readonly kind: 'none' }
  | { readonly kind: 'bool'; readonly value: boolean }
  | { readonly kind: 'int'; readonly value: bigint }
  | { readonly kind: 'float'; readonly value: number }
  | { readonly kind: 'str'; readonly value: string }
  | { readonly kind: 'tuple'; readonly items: readonly PyValue[] };

const NONE: PyValue = { kind: 'none' };

/**
 * The canonical string Python's `repr(_make_hashable(value))` produces for `value`.
 *
 * Deterministic across processes, runs and runtimes — which is what makes a durable archive key
 * built from it resolvable by a later session, by another pod, and by the Python worker running the
 * same flow.
 *
 * Throws {@link UnstableValueError} for a value with no Python counterpart at all (`undefined`, a
 * `bigint`, a function, a symbol, a `Date`) or no stable form (a circular reference), rather than
 * silently canonicalizing it to something no Python worker would ever produce.
 */
export const pythonRepr = (value: unknown): string => render(normalize(value, new Set<object>()));

// --- normalization (`_make_hashable`) ---------------------------------------------------

const normalize = (value: unknown, seen: Set<object>): PyValue => {
  switch (typeof value) {
    case 'string':
      return { kind: 'str', value };
    case 'number':
      // An integral number is indistinguishable from the Python `int` of the same value; see the
      // module docstring for the limit this imposes on a Python flow that holds it as a float.
      return Number.isInteger(value) ? { kind: 'int', value: BigInt(value) } : { kind: 'float', value };
    case 'boolean':
      return { kind: 'bool', value };
    case 'object':
      return value === null ? NONE : normalizeObject(value, seen);
    case 'undefined':
      throw new UnstableValueError(
        'undefined has no Python counterpart and cannot be part of a canonical value; use null',
      );
    case 'bigint':
      throw new UnstableValueError(
        'bigint has no JSON form and cannot be part of a canonical value; pass it as a string',
      );
    case 'function':
      throw new UnstableValueError('a function cannot be part of a canonical value');
    case 'symbol':
      throw new UnstableValueError('a symbol cannot be part of a canonical value');
    default:
      throw new UnstableValueError(`unsupported value of type ${typeof value} in a canonical value`);
  }
};

const normalizeObject = (value: object, seen: Set<object>): PyValue => {
  if (seen.has(value)) {
    throw new UnstableValueError('a circular reference cannot be part of a canonical value');
  }
  seen.add(value);
  try {
    if (value instanceof Date) {
      // `canonical_value` is specified over a JSON-native value. Python would repr a `datetime` as
      // `datetime.datetime(...)`, which no JSON document carries and which a `Date` could only be
      // mapped onto by inventing a convention — so a `Date` is refused here rather than given a
      // canonical form that silently disagrees with every Python worker. Pass an ISO string.
      throw new UnstableValueError(
        'a Date is not a JSON-native value and has no canonical form; pass its ISO-8601 string',
      );
    }
    if (Array.isArray(value)) {
      return { kind: 'tuple', items: value.map((item: unknown) => normalize(item, seen)) };
    }
    if (value instanceof Set) {
      // `tuple(sorted(...))`: membership is the identity, order is not — and a set and a list of
      // the same members in that order reduce to the same tuple in Python too.
      return { kind: 'tuple', items: sorted([...value].map((item: unknown) => normalize(item, seen))) };
    }
    if (value instanceof Map) {
      return normalizeItems(
        [...value].map(([key, item]) => ({ key: normalize(key, seen), value: normalize(item, seen) })),
      );
    }
    const custom = (value as { toJSON?: unknown }).toJSON;
    if (typeof custom === 'function') {
      // The escape hatch a class uses to say what it *is*, honoured exactly as JSON.stringify
      // honours it, so a model type has one serialization and not two.
      return normalize((custom as (this: object) => unknown).call(value), seen);
    }
    return normalizeItems(
      Object.keys(value).map((key) => ({
        key: { kind: 'str', value: key } as const,
        value: normalize((value as Record<string, unknown>)[key], seen),
      })),
    );
  } finally {
    // Removed on the way out so a value referenced twice side by side — a shared constant, not a
    // cycle — is normalized twice rather than rejected.
    seen.delete(value);
  }
};

/** One entry of a mapping, before the sort that makes the dict form canonical. */
interface NormalizedItem {
  readonly key: PyValue;
  readonly value: PyValue;
}

/** A mapping's `_make_hashable` form: `tuple(sorted((key, value) for ...))`. */
const normalizeItems = (items: readonly NormalizedItem[]): PyValue => ({
  kind: 'tuple',
  items: sorted(items.map((item): PyValue => ({ kind: 'tuple', items: [item.key, item.value] }))),
});

// --- Python's ordering ------------------------------------------------------------------

/**
 * `sorted(...)` — ascending and stable, with Python's comparison and Python's refusals.
 *
 * `Array.prototype.sort` is specified stable, and it calls the comparator not at all below two
 * elements, so a one-member set of a value Python could not have ordered (a bare `None`) sorts here
 * exactly as it sorts there: without comparing anything.
 */
const sorted = (items: readonly PyValue[]): readonly PyValue[] => [...items].sort(compare);

const TYPE_NAMES: Readonly<Record<PyValue['kind'], string>> = {
  none: 'NoneType',
  bool: 'bool',
  int: 'int',
  float: 'float',
  str: 'str',
  tuple: 'tuple',
};

/** Python's `<` over the normalized domain, as a comparator. */
const compare = (left: PyValue, right: PyValue): number => {
  if (left.kind === 'tuple' && right.kind === 'tuple') {
    return compareTuples(left.items, right.items);
  }
  if (left.kind === 'str' && right.kind === 'str') {
    return compareStrings(left.value, right.value);
  }
  const leftNumber = numberOf(left);
  const rightNumber = numberOf(right);
  if (leftNumber !== undefined && rightNumber !== undefined) {
    // A NaN compares false against everything, so Python's sort leaves it where it found it; a
    // comparator returning 0 does the same under a stable sort.
    if (Number.isNaN(leftNumber) || Number.isNaN(rightNumber) || leftNumber === rightNumber) {
      return 0;
    }
    return leftNumber < rightNumber ? -1 : 1;
  }
  // Python's TypeError, in the framework's own exception: two members of a set (or two dict items)
  // that Python could not have ordered have no canonical form here either.
  throw new UnstableValueError(
    `'<' not supported between instances of '${TYPE_NAMES[left.kind]}' and '${TYPE_NAMES[right.kind]}'`,
  );
};

/** The numeric view of a value Python treats as a number — `bool` is an `int` there. */
const numberOf = (value: PyValue): number | undefined => {
  switch (value.kind) {
    case 'bool':
      return value.value ? 1 : 0;
    case 'int':
      // Exact: every int here came from an integral double, so the round trip cannot lose a digit.
      return Number(value.value);
    case 'float':
      return value.value;
    default:
      return undefined;
  }
};

const compareTuples = (left: readonly PyValue[], right: readonly PyValue[]): number => {
  const shared = Math.min(left.length, right.length);
  for (let index = 0; index < shared; index += 1) {
    const leftItem = left[index];
    const rightItem = right[index];
    if (leftItem === undefined || rightItem === undefined) {
      break;
    }
    // Python compares element by element and only ever reaches the next pair when this one is
    // equal, which is why an unorderable pair deeper in two otherwise-equal tuples still raises.
    if (!equalValues(leftItem, rightItem)) {
      return compare(leftItem, rightItem);
    }
  }
  return left.length === right.length ? 0 : left.length < right.length ? -1 : 1;
};

/** Python's `==` over the normalized domain — what a tuple comparison consults before `<`. */
const equalValues = (left: PyValue, right: PyValue): boolean => {
  if (left.kind === 'tuple' && right.kind === 'tuple') {
    return (
      left.items.length === right.items.length &&
      left.items.every((item, index) => {
        const other = right.items[index];
        return other !== undefined && equalValues(item, other);
      })
    );
  }
  if (left.kind === 'str' || right.kind === 'str') {
    return left.kind === 'str' && right.kind === 'str' && left.value === right.value;
  }
  if (left.kind === 'none' || right.kind === 'none') {
    return left.kind === 'none' && right.kind === 'none';
  }
  const leftNumber = numberOf(left);
  const rightNumber = numberOf(right);
  return leftNumber !== undefined && rightNumber !== undefined && leftNumber === rightNumber;
};

/**
 * Python's `str` ordering: by **code point**.
 *
 * JavaScript's relational operators compare UTF-16 code units, which orders an astral character
 * (a surrogate pair, leading `\uD800`–`\uDBFF`) *before* U+E000–U+FFFF, where Python orders it
 * after. Sorting object keys that way would put a Python worker's Redis field and this one's in a
 * different order and split the identity.
 */
const compareStrings = (left: string, right: string): number => {
  if (left === right) {
    return 0;
  }
  const leftPoints = codePointsOf(left);
  const rightPoints = codePointsOf(right);
  const shared = Math.min(leftPoints.length, rightPoints.length);
  for (let index = 0; index < shared; index += 1) {
    const leftPoint = leftPoints[index] ?? 0;
    const rightPoint = rightPoints[index] ?? 0;
    if (leftPoint !== rightPoint) {
      return leftPoint < rightPoint ? -1 : 1;
    }
  }
  return leftPoints.length < rightPoints.length ? -1 : 1;
};

const codePointsOf = (value: string): readonly number[] =>
  [...value].map((character) => character.codePointAt(0) ?? 0);

// --- rendering (`repr`) -----------------------------------------------------------------

const render = (value: PyValue): string => {
  switch (value.kind) {
    case 'none':
      return 'None';
    case 'bool':
      return value.value ? 'True' : 'False';
    case 'int':
      return value.value.toString();
    case 'float':
      return pythonFloatRepr(value.value);
    case 'str':
      return pythonStrRepr(value.value);
    case 'tuple':
      return renderTuple(value.items);
    default: {
      const unreachable: never = value;
      throw new UnstableValueError(`unsupported normalized value ${String(unreachable)}`);
    }
  }
};

/** `repr(tuple)`: `()`, the trailing comma of a 1-tuple, and `', '` between the rest. */
const renderTuple = (items: readonly PyValue[]): string => {
  if (items.length === 0) {
    return '()';
  }
  const body = items.map(render).join(', ');
  return items.length === 1 ? `(${body},)` : `(${body})`;
};

/**
 * `repr(float)` — CPython's shortest round-tripping form.
 *
 * The digits are the shortest decimal that reads back as the same double, which is what
 * `Number.prototype.toExponential()` with no argument is specified to produce and what CPython's
 * `repr` takes from dtoa's shortest mode; the two agree digit for digit.
 *
 * The formatting is CPython's: fixed notation unless the decimal point would land at or before the
 * fourth leading zero or past the seventeenth digit (`decpt <= -4 || decpt > 16`, i.e. a scientific
 * exponent below -4 or at least 16), a trailing `.0` in fixed notation so the value still reads as
 * a float, and an exponent that always carries its sign and at least two digits (`1e-05`, `1e+16`,
 * `5e-324`).
 */
export const pythonFloatRepr = (value: number): string => {
  if (Number.isNaN(value)) {
    return 'nan';
  }
  if (value === Number.POSITIVE_INFINITY) {
    return 'inf';
  }
  if (value === Number.NEGATIVE_INFINITY) {
    return '-inf';
  }
  const sign = value < 0 || Object.is(value, -0) ? '-' : '';
  const scientific = Math.abs(value).toExponential();
  const separator = scientific.indexOf('e');
  const digits = scientific.slice(0, separator).replace('.', '');
  const exponent = Number(scientific.slice(separator + 1));
  // CPython's `decpt`: the position of the decimal point within the digit string.
  const pointPosition = exponent + 1;
  if (pointPosition <= -4 || pointPosition > 16) {
    const mantissa = digits.length > 1 ? `${digits.slice(0, 1)}.${digits.slice(1)}` : digits;
    const exponentSign = exponent < 0 ? '-' : '+';
    return `${sign}${mantissa}e${exponentSign}${String(Math.abs(exponent)).padStart(2, '0')}`;
  }
  if (pointPosition <= 0) {
    return `${sign}0.${'0'.repeat(-pointPosition)}${digits}`;
  }
  if (pointPosition >= digits.length) {
    return `${sign}${digits}${'0'.repeat(pointPosition - digits.length)}.0`;
  }
  return `${sign}${digits.slice(0, pointPosition)}.${digits.slice(pointPosition)}`;
};

/**
 * Non-printable in Python's sense: the Unicode `Other` and `Separator` categories.
 *
 * `str.isprintable()` is defined as "not in category Other or Separator, except the ASCII space",
 * and the space never reaches this test because it is emitted literally as an ASCII character
 * first. Unicode property escapes are the only way to ask JavaScript the same question.
 */
const NON_PRINTABLE = /^[\p{C}\p{Z}]$/u;

const hexEscape = (code: number): string => {
  if (code <= 0xff) {
    return `\\x${code.toString(16).padStart(2, '0')}`;
  }
  if (code <= 0xffff) {
    return `\\u${code.toString(16).padStart(4, '0')}`;
  }
  return `\\U${code.toString(16).padStart(8, '0')}`;
};

/**
 * `repr(str)` — CPython's `unicode_repr`.
 *
 * Single quotes, unless the string contains a `'` and no `"`, in which case double quotes avoid the
 * escape. Inside: the quote itself and the backslash are escaped, tab/newline/carriage return get
 * their short escapes, the remaining ASCII control characters and DEL become `\xhh`, and a
 * non-printable code point above ASCII becomes `\xhh`, `\uhhhh` or `\Uhhhhhhhh` by its width.
 * Everything printable — accents, CJK, astral emoji — is emitted literally, because CPython emits
 * `repr` as text and not as an ASCII escape (`ascii()` is the other function).
 */
export const pythonStrRepr = (value: string): string => {
  const quote = value.includes("'") && !value.includes('"') ? '"' : "'";
  let out = quote;
  // `for...of` walks code points, so an astral character is one iteration and a lone surrogate
  // stays the single code point Python's `str` would also hold.
  for (const character of value) {
    const code = character.codePointAt(0) ?? 0;
    if (character === quote || character === '\\') {
      out += `\\${character}`;
    } else if (character === '\t') {
      out += '\\t';
    } else if (character === '\n') {
      out += '\\n';
    } else if (character === '\r') {
      out += '\\r';
    } else if (code < 0x20 || code === 0x7f) {
      out += hexEscape(code);
    } else if (code < 0x7f) {
      out += character;
    } else if (NON_PRINTABLE.test(character)) {
      out += hexEscape(code);
    } else {
      out += character;
    }
  }
  return out + quote;
};
