/**
 * orcastork — a reusable, standalone dataflow orchestration framework.
 *
 * A blackboard/dataflow engine: `Operator`s consume and produce `DataPoint`s, `Capability`s
 * provide actions, `Aggregator`s write durable outputs, and a session-scoped `Orchestrator`
 * (supervised by a `SessionOrchestrationManager`) schedules work by data readiness rather than
 * fixed phases.
 *
 * The core is infrastructure- and domain-agnostic: it depends only on a set of `ports`
 * (interfaces); concrete backends (in-memory, Redis, Mongo) are injected as `adapters`. It is a
 * library, not a service: an embedding application runs it in its own event loop.
 *
 * This is the npm package's entry point, so unlike Python's empty `__init__.py` it has to name a
 * public surface: it re-exports each directory barrel's exports, which are themselves the mirrors
 * of the Python `__init__.py` files. The adapters are deliberately absent — a backend is imported
 * from `orcastork/adapters/...`, as `from orcastork.adapters.memory import ...` is in Python, so
 * reaching for the package root never drags one in.
 *
 * @module
 */

export {
  AggregateStatus,
  AggregationHelpers,
  type AggregationHelpersOptions,
  type BackoffOptions,
  backoffDelays,
  type OnAttempt,
  RetryPolicy,
  type RetryPolicyInit,
  type RunWithRetryOptions,
  retryPolicyBounds,
  runWithRetry,
  seedFor,
} from './aggregation/index.js';
export {
  ArchivedDataPoint,
  type ArchivedDataPointInit,
  type ArchivedDataPointWire,
  type ArchiveProvenance,
  type NamespaceCipherProvider,
  NullCipher,
  NullCipherProvider,
  parseArchivedDataPoint,
  seal,
  unseal,
  type ValueCipher,
  valueHash,
} from './archive/index.js';
export {
  AuditKind,
  AuditLogEntry,
  type AuditLogEntryInit,
  type AuditLogEntryWire,
  auditLogEntryToWire,
  CapabilityAuditInfo,
  type CapabilityAuditInfoInit,
  type CapabilityAuditInfoWire,
  DataPointAuditInfo,
  type DataPointAuditInfoInit,
  type DataPointAuditInfoWire,
  FlowAuditInfo,
  type FlowAuditInfoInit,
  type FlowAuditInfoWire,
  InboxAuditInfo,
  type InboxAuditInfoInit,
  type InboxAuditInfoWire,
  OperatorAuditInfo,
  type OperatorAuditInfoInit,
  type OperatorAuditInfoWire,
  OperatorOutcome,
  parseAuditLogEntry,
} from './audit/index.js';
export {
  Capability,
  CapabilityActivator,
  type CapabilityActivatorOptions,
  type CapabilityClass,
  CapabilityContext,
  type CapabilityContextInit,
  type CapabilityStatics,
  type ComputeAvailableOptions,
  type ConcreteCapabilityClass,
  type Credentials,
  capability,
  computeAvailable,
  type InvocationAuditor,
  type OnTerminalFailure,
} from './capabilities/index.js';
export { type Clock, SleepAbortedError, SystemClock } from './clock.js';
export {
  type AnyClass,
  type AnyDataPoint,
  type AnyDataPointClass,
  abstractDataPoint,
  abstractDataPointTypes,
  BaseDataPoint,
  type ConcreteDataPointClass,
  canonicalValue,
  type DataPointAdapter,
  type DataPointClass,
  DataPointEmission,
  type DataPointInit,
  type DataPointLeafClass,
  type DataPointSchemaKind,
  DataPointSet,
  type DataPointStatics,
  DataPointTypeConfig,
  type DataPointTypeConfigInit,
  type DataPointTypeOptions,
  DataPointView,
  type DataPointWire,
  dataPointAdapter,
  dataPointType,
  type EmissionProvenance,
  identityKey,
  isSubclass,
  MergeKind,
  type MergeResult,
  parseDataPoint,
  registeredLeaves,
  registryVersion,
  subtypesOf,
} from './datapoints/index.js';
export {
  AggregatorDeadLetteredError,
  CapabilityUnavailableError,
  CompletionTailTimeoutError,
  DuplicateRegistrationError,
  InvalidCapabilityError,
  InvalidCompletionConditionError,
  InvalidDataPointError,
  InvalidOperatorError,
  LockHeldError,
  OptimisticConcurrencyError,
  OrchestrationError,
  PiiKeyUnavailableError,
  ReplayError,
  SchedulingGateBlockedError,
  StaleEpochError,
  StateMirrorError,
  UnboundedCycleError,
  UnknownDataPointTypeError,
  UnprotectedPiiError,
  UnstableValueError,
} from './exceptions.js';
export { FlowDefinition, type FlowDefinitionInit, FlowIdentity } from './flow.js';
export {
  backwardReachable,
  buildGraph,
  buildUsesEdges,
  CircuitBreaker,
  type EdgeMap,
  findCycles,
  type Node,
  restrictToPermitted,
  validateAcyclicOrBounded,
} from './graph/index.js';
export {
  type Brand,
  CapabilityId,
  type DataPointType,
  Epoch,
  NamespaceId,
  newSessionId,
  OperatorId,
  OperatorRef,
  Revision,
  SessionId,
} from './ids.js';
export {
  type DescribeSessionOptions,
  describeSession,
  type OperatorState,
  renderText,
  type SessionDescription,
} from './introspection.js';
export { ConsoleJsonLogger, getLogger, type LogFields, type Logger, type LogLevel, setLogger } from './logging.js';
export { attachOtelLogBridge, detachOtelLogBridge, isOtelLogBridgeAttached } from './logging_bridge.js';
export {
  DEFAULT_REDELIVERY_RECHECK_MS,
  type DeliverOptions,
  MAX_BACKSTOP_RESPAWNS,
  type Redrive,
  type ResumeOptions,
  SchedulingGate,
  SessionOrchestrationManager,
  type SessionOrchestrationManagerOptions,
  type StartSessionOptions,
} from './manager/index.js';
export {
  Aggregator,
  type AggregatorClass,
  type AggregatorStatics,
  aggregator,
  CapabilityView,
  type ConcreteAggregatorClass,
  type ConcreteOperatorClass,
  type EffectBody,
  EffectGuard,
  type EffectGuardOptions,
  EffectRecovery,
  InvocationDelta,
  type InvocationDeltaInit,
  type OnceOptions,
  Operator,
  type OperatorClass,
  OperatorContext,
  type OperatorContextInit,
  OperatorPolicy,
  type OperatorPolicyInit,
  type OperatorStatics,
  operator,
  RerunOn,
} from './operators/index.js';
export {
  DEFAULT_EMISSION_QUEUE_SIZE,
  DEFAULT_LEASE_RENEW_INTERVAL_MS,
  DEFAULT_MAX_INBOX_DELIVERIES,
  DEFAULT_OPERATION_TIMEOUT_MS,
  DEFAULT_SESSION_DEADLINE_MS,
  type DeadLetter,
  type MirrorWriteResult,
  Orchestrator,
  type OrchestratorOptions,
  type OrchestratorResult,
  SessionStateMirror,
  SessionStatus,
  type Signal,
} from './orchestrator/index.js';
export {
  type ApplyResolvedOptions,
  type AuditSink,
  type CapabilityCatalog,
  ChangeSet,
  type ChangeSetInit,
  type ClaimEffectOptions,
  type ConsumeOptions,
  type CooldownGate,
  type DataPointArchive,
  type DataPointReader,
  type DataPointStore,
  type DeliveredInboxEntry,
  type DurableStore,
  type DurableUpsertOptions,
  EFFECT_COMMITTED,
  EFFECT_PENDING_PREFIX,
  EffectClaim,
  effectPendingEpoch,
  effectPendingState,
  type Inbox,
  InboxEntry,
  type InboxEntryInit,
  NullRateLimiter,
  PoisonInboxEntry,
  type PoisonInboxEntryInit,
  QuarantinedEntry,
  type QuarantinedEntryInit,
  type QuarantineOptions,
  type RateLimiter,
  type SessionLock,
  VersionedDocument,
  type VersionedDocumentInit,
} from './ports/index.js';
export { type ReplayResult, type ReplaySessionOptions, replaySession } from './replay.js';
export { buildInMemoryRuntime, OrchestratorRuntime, type OrchestratorRuntimeInit } from './runtime.js';
export {
  AllOf,
  AnyOf,
  allOf,
  anyOf,
  type CompletionCondition,
  type CompletionItem,
  type ComputeDeltaOptions,
  computeDelta,
  DEFAULT_DEBOUNCE_MS,
  DebounceController,
  type DebounceControllerOptions,
  describeCondition,
  type FinalizeProximity,
  isQuiescent,
  isReady,
  normalizeCompletion,
  type OperatorDeltaOptions,
  operatorDelta,
  type ReadinessGap,
  type ReadinessInputs,
  type ReadyOperatorsOptions,
  type RerunEligibilityInputs,
  reachablePending,
  readinessGap,
  readyOperators,
  referencedTypes,
  rerunEligible,
  TypePresent,
  type WindowOptions,
  windowDefersToFinalize,
} from './scheduling/index.js';
export { Telemetry, type TelemetryOptions, type WithSpanOptions, withSpan } from './telemetry.js';
