#!/usr/bin/env python3.13
"""Generate ``python_repr_fixtures.json`` — the CPython oracle for ``internal/python_repr.ts``.

The TypeScript ``pythonRepr`` has to reproduce ``repr(_make_hashable(value))`` byte for byte,
because that string is a Redis hash field and the input to the archive key's digest (see
``orcastork/datapoints/base.py`` and ``orcastork/archive/sealing.py``). The only honest oracle for
"what does CPython print" is CPython, so this script prints it, and the vitest suite asserts
against the table rather than against a second implementation of the rules.

Run it with Python 3.13 (stdlib only), from this directory::

    python3.13 python_repr_fixtures.py

Each value is carried in a form **both** runtimes parse identically:

``repr`` rows
    a JSON document. Python ``json.loads`` it, TypeScript ``JSON.parse``s it, and the two agree on
    every JSON-native value — except the one thing JavaScript cannot represent: it has a single
    number type, so a float whose value is integral is indistinguishable from the int. Those rows
    carry ``expected_js`` as well, which is the repr of the same value with every integral float
    replaced by that int — still CPython's repr, of a value adjusted by the one documented
    coercion, so the oracle is never a reimplementation of the port.

``float`` rows
    a decimal literal. ``float(literal)`` and ``Number(literal)`` produce the same double, so the
    formatting rules (shortest digits, the fixed-vs-exponent switch, the padded exponent, the
    infinities and NaN) are pinned without JSON's int/float ambiguity in the way.

``str`` rows
    a JSON string literal, so every escape is unambiguous on both sides.
"""

from __future__ import annotations

import json
import math
from pathlib import Path
from typing import Any

# Copied verbatim from ``orcastork/datapoints/base.py`` — the fixtures must be generated by the
# function under specification, not by a paraphrase of it.
def _make_hashable(obj: Any) -> Any:
    """Recursively coerce a value into a hashable form (lists/dicts/sets → tuples)."""
    if isinstance(obj, (list, tuple)):
        return tuple(_make_hashable(item) for item in obj)
    if isinstance(obj, dict):
        return tuple(sorted((key, _make_hashable(value)) for key, value in obj.items()))
    if isinstance(obj, (set, frozenset)):
        return tuple(sorted(_make_hashable(item) for item in obj))
    return obj


def canonical_value(value: Any) -> str:
    """The function under specification (``orcastork.datapoints.canonical_value``)."""
    return repr(_make_hashable(value))


def as_js_number_domain(obj: Any) -> Any:
    """The value as JavaScript can see it: one number type, and that type is a double.

    Two coercions, both of them inherent to the runtime and neither of them fixable: an integral
    float is indistinguishable from the int of the same value, and an int beyond 2**53 rounds to
    the nearest double. Applying them here and then taking CPython's own repr keeps the expectation
    an oracle rather than a second implementation of the port.
    """
    if isinstance(obj, bool):
        return obj
    if isinstance(obj, float) and math.isfinite(obj) and obj.is_integer():
        return int(obj)
    if isinstance(obj, int) and abs(obj) > 2**53:
        return int(float(obj))
    if isinstance(obj, list):
        return [as_js_number_domain(item) for item in obj]
    if isinstance(obj, dict):
        return {key: as_js_number_domain(value) for key, value in obj.items()}
    return obj


# --- the table ---------------------------------------------------------------------------

# (id, JSON document). Parsed by both runtimes; the expectation is CPython's repr of the result.
REPR_ROWS: list[tuple[str, str]] = [
    # scalars
    ('null', 'null'),
    ('true', 'true'),
    ('false', 'false'),
    ('int-zero', '0'),
    ('int-negative', '-1'),
    ('int-small', '42'),
    ('int-2-53', '9007199254740992'),
    ('int-beyond-2-53', '9007199254740993'),
    ('int-negative-2-53', '-9007199254740992'),
    ('int-json-minus-zero', '-0'),
    ('float-tenth', '0.1'),
    ('float-negative-tenth', '-0.1'),
    ('float-third', '0.3333333333333333'),
    ('float-mixed', '123456789.123'),
    ('float-half', '0.5'),
    ('float-1e-4', '0.0001'),
    ('float-1e-5', '1e-5'),
    ('float-5e-324', '5e-324'),
    ('float-1e16-is-integral-in-js', '1e16'),
    ('float-1e21-is-integral-in-js', '1e21'),
    ('float-one-point-zero-is-integral-in-js', '1.0'),
    ('float-minus-zero-is-integral-in-js', '-0.0'),
    ('float-2e3-is-integral-in-js', '2.0e3'),
    # strings
    ('str-empty', '""'),
    ('str-plain', '"hello"'),
    ('str-with-space', '"hello world"'),
    ('str-single-quote', '"it\'s"'),
    ('str-double-quote', '"say \\"hi\\""'),
    ('str-both-quotes', '"both \' and \\""'),
    ('str-backslash', '"a\\\\b"'),
    ('str-newline', '"line1\\nline2"'),
    ('str-tab-cr', '"a\\tb\\rc"'),
    ('str-control', '"bell:\\u0007 null:\\u0000 del:\\u007f"'),
    ('str-accented', '"caf\\u00e9"'),
    ('str-nbsp', '"a\\u00a0b"'),
    ('str-emoji', '"\\ud83d\\ude00"'),
    ('str-emoji-zwj-sequence', '"\\ud83d\\udc69\\u200d\\ud83d\\udcbb"'),
    ('str-rtl-marks', '"\\u200f\\u0627\\u0644\\u0639\\u0631\\u0628\\u064a\\u0629\\u200e"'),
    ('str-cjk', '"\\u6f22\\u5b57"'),
    ('str-private-use', '"\\ue000"'),
    ('str-line-separator', '"a\\u2028b"'),
    ('str-astral-non-emoji', '"\\ud840\\udc0b"'),
    ('str-replacement-character', '"\\ufffd"'),
    # arrays → tuples
    ('list-empty', '[]'),
    ('list-one', '[1]'),
    ('list-two', '[1, 2]'),
    ('list-of-strings', '["x", "y", "z"]'),
    ('list-order-matters', '["y", "x"]'),
    ('list-nested', '[[1, 2], [3]]'),
    ('list-one-nested-empty', '[[]]'),
    ('list-mixed', '[1, "two", true, null, 3.5]'),
    ('list-of-objects', '[{"b": 1, "a": 2}, {"a": 1}]'),
    # objects → sorted tuples of pairs
    ('object-empty', '{}'),
    ('object-one', '{"a": 1}'),
    ('object-unsorted', '{"b": 1, "a": 2}'),
    ('object-sorted', '{"a": 2, "b": 1}'),
    ('object-nested-unsorted', '{"b": 1, "a": {"d": 4, "c": 3}}'),
    ('object-deep', '{"outer": {"inner": {"leaf": [1, 2]}}}'),
    ('object-value-empty-containers', '{"list": [], "object": {}}'),
    ('object-numeric-looking-keys', '{"10": "ten", "9": "nine", "1": "one"}'),
    ('object-keys-needing-escapes', '{"a\\nb": 1, "a\'b": 2, "a\\\\b": 3}'),
    ('object-empty-key', '{"": 1}'),
    ('object-astral-vs-bmp-keys', '{"z": 0, "\\u00e9": 1, "\\ufffd": 2, "\\ud83d\\ude00": 3, "\\ue000": 4}'),
    ('object-key-prefix-order', '{"ab": 1, "a": 2, "b": 3}'),
    ('object-with-mixed-values', '{"n": null, "t": true, "f": false, "i": 7, "x": 0.25, "s": "q"}'),
    # the shapes the DataPoint zoo actually carries
    ('geo-like', '{"lat": 51.5, "lon": -0.12}'),
    ('geo-like-reordered', '{"lon": -0.12, "lat": 51.5}'),
    ('tags-like', '{"tags": ["x", "y"], "groups": []}'),
    ('deeply-nested-mixed', '{"a": [{"b": [1, {"c": null}]}], "d": {"e": []}}'),
]

# (id, decimal literal). ``float(literal)`` and ``Number(literal)`` are the same double.
FLOAT_ROWS: list[tuple[str, str]] = [
    ('zero', '0.0'),
    ('negative-zero', '-0.0'),
    ('one', '1.0'),
    ('minus-one', '-1.0'),
    ('tenth', '0.1'),
    ('two-thirds', '0.6666666666666666'),
    ('mixed', '123456789.123'),
    ('negative-mixed', '-123456789.123'),
    ('1e-4-is-fixed', '1e-4'),
    ('1e-5-switches-to-exponent', '1e-5'),
    ('1.5e-7', '1.5e-7'),
    ('smallest-subnormal', '5e-324'),
    ('1e15-is-fixed', '1e15'),
    ('largest-fixed', '9999999999999998.0'),
    ('1e16-switches-to-exponent', '1e16'),
    ('1.7976931348623157e308', '1.7976931348623157e308'),
    ('1e21', '1e21'),
    ('1e100', '1e100'),
    ('1.5e300', '1.5e300'),
    ('negative-1e16', '-1e16'),
    ('fraction-at-the-fixed-edge', '4503599627370495.5'),
    ('nan', 'NaN'),
    ('infinity', 'Infinity'),
    ('negative-infinity', '-Infinity'),
]

# (id, JSON string literal). Parsed to a str by both runtimes; the expectation is ``repr(str)``.
STR_ROWS: list[tuple[str, str]] = [
    ('empty', '""'),
    ('ascii', '"plain ascii"'),
    ('single-quote-only', '"it\'s"'),
    ('double-quote-only', '"she said \\"no\\""'),
    ('both-quotes', '"it\'s \\"fine\\""'),
    ('backslash', '"C:\\\\path\\\\to"'),
    ('backslash-and-quote', '"\\\\\'"'),
    ('newline', '"a\\nb"'),
    ('carriage-return', '"a\\rb"'),
    ('tab', '"a\\tb"'),
    ('form-feed-and-vertical-tab', '"\\u000c\\u000b"'),
    ('nul', '"\\u0000"'),
    ('escape-and-del', '"\\u001b\\u007f"'),
    ('every-ascii-control', '"' + ''.join(f'\\u{code:04x}' for code in range(0x20)) + '"'),
    ('latin-1-supplement-printable', '"\\u00e9\\u00df\\u00ff"'),
    ('nbsp-is-not-printable', '"\\u00a0"'),
    ('soft-hyphen-is-not-printable', '"\\u00ad"'),
    ('zero-width-joiner', '"\\u200d"'),
    ('zero-width-space', '"\\u200b"'),
    ('rtl-mark', '"\\u200f"'),
    ('lrm-and-arabic', '"\\u200e\\u0627"'),
    ('line-separator', '"\\u2028"'),
    ('paragraph-separator', '"\\u2029"'),
    ('ideographic-space', '"\\u3000"'),
    ('private-use-bmp', '"\\ue000"'),
    ('replacement-character', '"\\ufffd"'),
    ('noncharacter-fffe', '"\\ufffe"'),
    ('bom', '"\\ufeff"'),
    ('emoji', '"\\ud83d\\ude00"'),
    ('family-zwj-sequence', '"\\ud83d\\udc68\\u200d\\ud83d\\udc69\\u200d\\ud83d\\udc66"'),
    ('astral-cjk-extension', '"\\ud840\\udc0b"'),
    ('astral-private-use', '"\\udbff\\udffd"'),
    ('astral-tag-character', '"\\udb40\\udc61"'),
    ('lone-surrogate', '"\\ud800"'),
    ('mixed-scripts', '"caf\\u00e9 \\u6f22\\u5b57 \\ud83d\\ude00 \\u0627\\u0644\\u0639"'),
    ('mixed-escapes-and-text', '"tab\\there\\nand \\"quoted\\" \\u00e9\\u200d"'),
]


def repr_rows() -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    for row_id, document in REPR_ROWS:
        value = json.loads(document)
        expected = canonical_value(value)
        row = {'id': row_id, 'json': document, 'expected': expected}
        expected_js = canonical_value(as_js_number_domain(value))
        if expected_js != expected:
            row['expected_js'] = expected_js
        rows.append(row)
    return rows


def float_rows() -> list[dict[str, str]]:
    return [{'id': row_id, 'literal': literal, 'expected': repr(float(literal))} for row_id, literal in FLOAT_ROWS]


def str_rows() -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    for row_id, document in STR_ROWS:
        value = json.loads(document)
        assert isinstance(value, str)
        rows.append({'id': row_id, 'json': document, 'expected': repr(value)})
    return rows


def main() -> None:
    import sys

    fixtures = {
        'generated_by': 'tests/internal/python_repr_fixtures.py',
        'python_version': sys.version.split()[0],
        'repr': repr_rows(),
        'float': float_rows(),
        'str': str_rows(),
    }
    destination = Path(__file__).with_name('python_repr_fixtures.json')
    destination.write_text(json.dumps(fixtures, indent=2, ensure_ascii=True) + '\n', encoding='utf-8')
    total = len(fixtures['repr']) + len(fixtures['float']) + len(fixtures['str'])
    print(f'wrote {total} fixtures to {destination}')


if __name__ == '__main__':
    main()
